FROM ubuntu:focal
RUN DEBIAN_FRONTEND=noninteractive ln -fs /usr/share/zoneinfo/Europe/Kaliningrad /etc/localtime; apt-get -y update; apt-get -y install software-properties-common unzip openssh-client wget rsync curl git;\
    LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php; apt-get -y install php7.4-cli php7.4-curl php7.4-zip php8.0-cli php-pear php8.0-curl;\
    curl -sL https://deb.nodesource.com/setup_16.x | bash - ;\
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -;\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list;\
    apt-get -y update;\
    apt-get -y install nodejs yarn g++ gcc make
